[build]
  command = "npm run build"
  publish = ".output/public"

[functions]
  included_files = ["static/*"]

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/account"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200