[build]
  command = "npm run build"
  publish = "dist"

[functions]
  included_files = ["static/users.json"]

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/account"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200